export const ERROR_CODES = {
  // Authentication
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',
  AUTH_USER_NOT_FOUND: 'AUTH_USER_NOT_FOUND',
  AUTH_USER_INACTIVE: 'AUTH_USER_INACTIVE',
  AUTH_PASSWORD_WEAK: 'AUTH_PASSWORD_WEAK',

  // Validation
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_INPUT: 'INVALID_INPUT',
  REQUIRED_FIELD: 'REQUIRED_FIELD',
  DUPLICATE_ENTRY: 'DUPLICATE_ENTRY',

  // Business Logic
  INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  RESOURCE_LOCKED: 'RESOURCE_LOCKED',
  INVALID_STATUS: 'INVALID_STATUS',
  INVALID_OPERATION: 'INVALID_OPERATION',

  // Finance
  INVOICE_ALREADY_PAID: 'INVOICE_ALREADY_PAID',
  INVOICE_OVERDUE: 'INVOICE_OVERDUE',
  CREDIT_LIMIT_EXCEEDED: 'CREDIT_LIMIT_EXCEEDED',
  PERIOD_CLOSED: 'PERIOD_CLOSED',
  UNBALANCED_ENTRY: 'UNBALANCED_ENTRY',

  // Inventory
  INSUFFICIENT_STOCK: 'INSUFFICIENT_STOCK',
  NEGATIVE_STOCK: 'NEGATIVE_STOCK',
  ITEM_INACTIVE: 'ITEM_INACTIVE',

  // Integration
  EXTERNAL_API_ERROR: 'EXTERNAL_API_ERROR',
  PAYMENT_GATEWAY_ERROR: 'PAYMENT_GATEWAY_ERROR',
  CRM_SYNC_FAILED: 'CRM_SYNC_FAILED',

  // System
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  DATABASE_ERROR: 'DATABASE_ERROR',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
