-- Generated from discover-output.json (SQL Server ATS_GL -> PostgreSQL iteck_erp)
-- Option A: keep SQL Server table/column names (quoted where needed)
-- Run 00-iteck_erp-init.sql first (e.g. CREATE EXTENSION uuid-ossp)

CREATE TABLE IF NOT EXISTS "update_Ar_Order_Price" (
  "AO_NO" INTEGER NOT NULL,
  "AO_PRICE2" DOUBLE PRECISION,
  "AO_PRICE3" DOUBLE PRECISION,
  "AO_PRICE4" DOUBLE PRECISION,
  "AO_PRICE5" DOUBLE PRECISION,
  "AO_PRICE6" DOUBLE PRECISION,
  "AO_PRICE7" DOUBLE PRECISION,
  "AO_PRICE8" DOUBLE PRECISION,
  "AO_PRICE9" DOUBLE PRECISION,
  "AO_PRICE10" DOUBLE PRECISION,
  "AO_PRICE11" DOUBLE PRECISION,
  "AO_PRICE12" DOUBLE PRECISION,
  "SeqNo" INTEGER,
  "ElementID" INTEGER
);

CREATE TABLE IF NOT EXISTS sysdiagrams (
  name VARCHAR(128) NOT NULL,
  principal_id INTEGER NOT NULL,
  diagram_id INTEGER NOT NULL,
  version INTEGER,
  definition BYTEA
);

CREATE TABLE IF NOT EXISTS payment_sms (
  "SNo" INTEGER NOT NULL,
  "APR_NO" BIGINT NOT NULL,
  "APR_DATE" TIMESTAMP,
  "SMS_SEND" BOOLEAN
);

CREATE TABLE IF NOT EXISTS "je_Data_LOG" (
  "USERID" INTEGER,
  "Entry_date" TIMESTAMP,
  "STATEMENT" VARCHAR(8000),
  navistatus INTEGER,
  logid BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS "Users" (
  id INTEGER NOT NULL,
  username VARCHAR(50) NOT NULL,
  password VARCHAR(255) NOT NULL,
  full_name VARCHAR(100) NOT NULL,
  email VARCHAR(100),
  role VARCHAR(20),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  is_active BOOLEAN
);

CREATE TABLE IF NOT EXISTS "User_Resp" (
  "UR_ID" INTEGER NOT NULL,
  "USERID" INTEGER NOT NULL,
  "RESPID" INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS "UserLogin" (
  "USERID" INTEGER NOT NULL,
  "USERNAME" VARCHAR(50) NOT NULL,
  "PASSWORD" VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS "Update_AR_ORDER_AO_DATE" (
  "AO_NO" BIGINT,
  "AI_INV_DATE" TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "Update_AR_Invoice_Co_ID" (
  "APR_NO" BIGINT,
  "APR_DESCRIPTION" VARCHAR(200)
);

CREATE TABLE IF NOT EXISTS "Update_AR_INVOICE_INFO_SELECTED" (
  "AI_AO_NO" VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS "USER_MENU_ASSIGN" (
  "UA_ID" BIGINT NOT NULL,
  "UA_UserID" INTEGER NOT NULL,
  "UA_MENU_ID" BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS "Test_TB_Eng_Reg_Ch_Search" (
  "AI_VEHICLE_ENGINENO" VARCHAR(50),
  "AI_VEHICLE_REGISTRATIONNO" VARCHAR(50),
  "AI_VEHICLE_CHASISNO" VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS "TAX_MASTER" (
  "TM_ID" INTEGER NOT NULL,
  "TM_DESCRIPTION" VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS "TAX_DETAIL" (
  "TD_ID" INTEGER NOT NULL,
  "TD_ACTIVE_ON" TIMESTAMP NOT NULL,
  "TD_DESCRIPTION" VARCHAR(50) NOT NULL,
  "TD_AC_ID" BIGINT NOT NULL,
  "TD_AGE" DOUBLE PRECISION NOT NULL,
  "TD_TM_ID" INTEGER NOT NULL,
  "TD_WHT" BIGINT
);

CREATE TABLE IF NOT EXISTS "SUB_ACCOUNT" (
  "SA_ID" CHAR(4) NOT NULL,
  "SA_NAME" VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS "Responsibilties" (
  "RESPID" INTEGER NOT NULL,
  "RESPNAME" VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS "Period_Closing" (
  "Period_Close_date" TIMESTAMP,
  "Period_Close_on" TIMESTAMP,
  "period_Close_by" INTEGER
);

CREATE TABLE IF NOT EXISTS "PaymentReceipts_For_CRM_Dashboard" (
  "APR_NO" VARCHAR(50),
  "APR_DATE" TIMESTAMP,
  "APR_DESCRIPTION" VARCHAR(255),
  "APR_CO_ID" INTEGER,
  "APR_BANK_ID" INTEGER,
  "APR_POST" BOOLEAN,
  "APR_GL" BOOLEAN,
  "APR_Cancel" BOOLEAN,
  "AAI_AI_NO" VARCHAR(50),
  "AAI_AI_DATE" TIMESTAMP,
  "AAI_AI_AMOUNT" NUMERIC(18,2),
  "AAI_PEN_AMOUNT" NUMERIC(18,2),
  "AAI_ADJUST" NUMERIC(18,2),
  "AO_VEHICLE_ID" VARCHAR(50),
  "AI_vehicle_make" VARCHAR(100),
  "AI_VEHICLE_MODEL" VARCHAR(100),
  "AI_VEHICLE_CHASISNO" VARCHAR(100),
  "AI_VEHICLE_ENGINENO" VARCHAR(100),
  "AI_VEHICLE_DOI" TIMESTAMP,
  "AI_VEHICLE_REGISTRATIONNO" VARCHAR(100),
  "CRM_TRANS_ID" INTEGER,
  "BANK_NAME" VARCHAR(100),
  "CO_Company_Name" VARCHAR(200),
  "CRM_InsuredBy" VARCHAR(200),
  "CRM_CustomerName" VARCHAR(200)
);

CREATE TABLE IF NOT EXISTS "PI_Issuance_Item_Serial_Nos" (
  "IDSRM_No" INTEGER NOT NULL,
  "PI_Item_Combination_ID" INTEGER NOT NULL,
  "IDSRM_TYPE" VARCHAR(50) NOT NULL,
  "Iss_Dtl_Qty" DOUBLE PRECISION NOT NULL,
  "DS_No" VARCHAR(50) NOT NULL,
  "IDSRM_ID" INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS "PI_Issuance_Diag_Item_Serial_Nos" (
  "IDSRM_No" INTEGER NOT NULL,
  "PI_Item_Combination_ID" INTEGER NOT NULL,
  "IDSRM_TYPE" VARCHAR(50) NOT NULL,
  "Iss_Dtl_Qty" DOUBLE PRECISION NOT NULL,
  "DS_No" VARCHAR(50) NOT NULL,
  "IDSRM_ID" INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS "PI_Issuance_Diag" (
  "IDSRM_No" INTEGER NOT NULL,
  "IDSRM_Date" TIMESTAMP NOT NULL,
  "Item_Type" VARCHAR(10) NOT NULL,
  "IDSRM_Remarks" VARCHAR(255),
  "PI_Item_Combination_ID" INTEGER NOT NULL,
  "Iss_Qty" DOUBLE PRECISION NOT NULL,
  "IDSRM_Post" BOOLEAN,
  "IDSRM_Cancel" BOOLEAN
);

CREATE TABLE IF NOT EXISTS "PI_Issuance" (
  "IDSRM_No" INTEGER NOT NULL,
  "IDSRM_Date" TIMESTAMP NOT NULL,
  "Item_Type" VARCHAR(10) NOT NULL,
  "IDSRM_Remarks" VARCHAR(255),
  "PI_Item_Combination_ID" INTEGER NOT NULL,
  "Iss_Qty" DOUBLE PRECISION NOT NULL,
  "IDSRM_Post" BOOLEAN,
  "IDSRM_Cancel" BOOLEAN
);

CREATE TABLE IF NOT EXISTS "PI_Invoice_Item_Serial_Nos" (
  "PI_NO" INTEGER,
  "PI_Item_Combination_ID" INTEGER,
  "Item_Type" VARCHAR(10),
  "D_Serial_No" VARCHAR(20),
  "D_IMEI_No" VARCHAR(20),
  "S_SIM_No" VARCHAR(20),
  "S_IMEI_No" VARCHAR(20),
  "S_ICCID_No" VARCHAR(20),
  "S_MSISDN_No" VARCHAR(20),
  "PIID" INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS "PI_INVOICE" (
  "PI_NO" BIGINT NOT NULL,
  "PI_DATE" TIMESTAMP,
  "PI_Pur_Type" VARCHAR(50),
  "PI_REMARKS" VARCHAR(100),
  "PI_SUPPLIER_REF" VARCHAR(50),
  "PI_Item_Combination_ID" BIGINT,
  "PI_AC_ID" INTEGER,
  "PI_RMKS" VARCHAR(200),
  "PI_QTY" DOUBLE PRECISION,
  "PI_RATE" DOUBLE PRECISION,
  "PI_AMOUNT" DOUBLE PRECISION,
  "PI_GST" DOUBLE PRECISION,
  "PI_AST" DOUBLE PRECISION,
  "PI_NET_AMOUNT" DOUBLE PRECISION,
  "PI_TYPE" VARCHAR(50),
  "PI_POST" BOOLEAN,
  "PI_AS_ID" INTEGER,
  "PI_CANCEL" BOOLEAN,
  "PI_CANCEL_DATE" TIMESTAMP,
  "PI_INV_GL" BOOLEAN,
  "PI_CAN_GL" BOOLEAN,
  "PI_PAY_TO" VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS "Organizational_Unit" (
  "ORG_ID" CHAR(4) NOT NULL,
  "ORG_NAME" VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS "NotesMaster" (
  "NoteID" DOUBLE PRECISION NOT NULL,
  "COMBINATION_ID" BIGINT NOT NULL,
  "NoteDetail" VARCHAR(150),
  "NoteCategory" VARCHAR(50),
  "NoteDescription" VARCHAR(200)
);

CREATE TABLE IF NOT EXISTS "NATURAL_ACCOUNT" (
  "NA_ID" CHAR(6) NOT NULL,
  "NA_NAME" VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS "Menu_option" (
  menu_id BIGINT NOT NULL,
  menu_respid INTEGER NOT NULL,
  menu_option_key VARCHAR(50) NOT NULL,
  menu_option_name VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS "LastMonthSummary" (
  "ATS_Date" DATE,
  "Bank Islami Pakistan Limited" NUMERIC(38,2) NOT NULL,
  "Dubai Islamic Bank Limited" NUMERIC(38,2) NOT NULL,
  "Meezan Bank Limited" NUMERIC(38,2) NOT NULL,
  "Total" NUMERIC(38,2)
);

CREATE TABLE IF NOT EXISTS "INV_UnitOfMeasure" (
  "UOM_ID" INTEGER NOT NULL,
  "UOM_Code" VARCHAR(50),
  "UOM_Descr" VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS "INV_Requisition" (
  "Req_No" BIGINT NOT NULL,
  "Req_Date" TIMESTAMP,
  "Remarks" VARCHAR(100),
  "Product_ID" BIGINT,
  "Req_Qty" DOUBLE PRECISION,
  "Admin_Qty" DOUBLE PRECISION,
  "SeqNO" BIGINT
);

CREATE TABLE IF NOT EXISTS "INV_Packing" (
  "PK_ID" INTEGER NOT NULL,
  "PK_Descr" VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS "INV_LOC_ITEM_OPEN" (
  "ILIO" BIGINT NOT NULL,
  "GDID" VARCHAR(3) NOT NULL,
  "ITEM" BIGINT NOT NULL,
  "OP_BAL_Q" DOUBLE PRECISION,
  "OP_RATE" DOUBLE PRECISION
);

CREATE TABLE IF NOT EXISTS "INV_LOCATION" (
  "GDID" VARCHAR(3) NOT NULL,
  "GDNAME" VARCHAR(50),
  "GDADDRESS" VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS "INV_Item_Sub_Category" (
  "ISC_Combination_ID" INTEGER NOT NULL,
  "IC_ID" INTEGER,
  "IC_Descr" VARCHAR(100),
  "ISC_ID" INTEGER NOT NULL,
  "ISC_Descr" VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS "INV_Item_Mstr" (
  "Item_Combination_ID" INTEGER NOT NULL,
  "ISC_Combination_ID" INTEGER NOT NULL,
  "IC_ID" INTEGER NOT NULL,
  "ISC_ID" INTEGER NOT NULL,
  "Item_ID" BIGINT NOT NULL,
  "Item_Code" VARCHAR(10) NOT NULL,
  "Item_Descr" VARCHAR(200),
  "IC_AC_ID" INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS "INV_ITEM" (
  product_id BIGINT NOT NULL,
  product_name VARCHAR(50) NOT NULL,
  product_um VARCHAR(50),
  "Type" VARCHAR(50),
  product_ac_id INTEGER
);

CREATE TABLE IF NOT EXISTS "INV_ENTRY" (
  "IE_ID" BIGINT NOT NULL,
  "JV_NO" BIGINT,
  "TYPE" VARCHAR(3),
  "DATE" TIMESTAMP,
  "IE_TYPE" VARCHAR(50),
  "CO_ID" INTEGER,
  "REMARKS" VARCHAR(50),
  "HarRcpt" BOOLEAN,
  "ITEM" BIGINT,
  "Item_Type" VARCHAR(50),
  "Item_Serial_Voice_No" VARCHAR(50),
  "RecDate" TIMESTAMP,
  "Status" VARCHAR(50),
  "QTY" DOUBLE PRECISION,
  "Others" VARCHAR(100),
  "TGDID" VARCHAR(3),
  "FGDID" VARCHAR(3),
  "SerialNo" VARCHAR(50),
  "VoiceNo" VARCHAR(50),
  "ReceiverName" VARCHAR(50),
  "RegistrationNo" VARCHAR(50),
  "EngineNo" VARCHAR(50),
  "ChasisNo" VARCHAR(50),
  "ModelNo" VARCHAR(50),
  "SeqNo" BIGINT
);

CREATE TABLE IF NOT EXISTS "INV_Contain" (
  "CONT_ID" INTEGER NOT NULL,
  "CONT_Descr" INTEGER
);

CREATE TABLE IF NOT EXISTS "INV_Configuration" (
  "Config_No" BIGINT NOT NULL,
  "Config_Date" TIMESTAMP,
  "Remarks" VARCHAR(100),
  "D_Product_ID" BIGINT,
  "Serial_No" VARCHAR(50),
  "S_Product_ID" BIGINT,
  "Voice_No" VARCHAR(50),
  "TGDID" VARCHAR(3),
  "SeqNo" INTEGER
);

CREATE TABLE IF NOT EXISTS "INV_BOM" (
  "IB_ID" BIGINT NOT NULL,
  "FIN_ITEM_ID" BIGINT,
  "RAW_ITEM" BIGINT,
  "QTY" DOUBLE PRECISION
);

CREATE TABLE IF NOT EXISTS "GL_JE_LINE_UPDATE_DATE" (
  "JE_LINE_ID" BIGINT,
  "JE_HEADER_ID" BIGINT,
  "JE_AC_ID" INTEGER,
  "JE_ENTERED_DR" BIGINT,
  "JE_ENTERED_CR" BIGINT
);

CREATE TABLE IF NOT EXISTS "GL_JE_LINES_ALL" (
  "JE_LINE_ID" BIGINT NOT NULL,
  "JE_HEADER_ID" BIGINT NOT NULL,
  "JE_AC_ID" BIGINT NOT NULL,
  "JE_ENTERED_DR" DOUBLE PRECISION,
  "JE_ENTERED_CR" DOUBLE PRECISION,
  "JE_DESCRIPTION_LINE" VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS "GL_JE_HEADER_ALL" (
  "JE_HEADER_ID" BIGINT NOT NULL,
  "JE_VOUCHER_NO" BIGINT,
  "JE_DATE" TIMESTAMP NOT NULL,
  "JE_DESCRIPTION" VARCHAR(255) NOT NULL,
  "JE_TYPE" VARCHAR(50) NOT NULL,
  "JE_POST_FLAG" BOOLEAN,
  "JE_CREATED_BY" INTEGER,
  "JE_CREATED_DATE" TIMESTAMP,
  "JE_UPDATED_BY" INTEGER,
  "JE_UPDATED_DATE" TIMESTAMP,
  "JE_NAME" VARCHAR(150)
);

CREATE TABLE IF NOT EXISTS "Data_Entry_LOG" (
  "VCH_NO" BIGINT,
  "VCH_TYPE" VARCHAR(50),
  "PC_INSERT" VARCHAR(50),
  "LOG_DATETIME_INSERT" TIMESTAMP,
  "PC_UPDATE" VARCHAR(50),
  "LOG_DATETIME_UPDATE" TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "DashboardSummaryMasterData" (
  "TYPE" VARCHAR(19) NOT NULL,
  "APR_NO" BIGINT NOT NULL,
  "ATS_Date" DATE,
  "APR_BANK_ID" INTEGER,
  "BANK_NAME" VARCHAR(100) NOT NULL,
  "Tot_Receipt_Amt" DOUBLE PRECISION,
  "APR_CO_ID" BIGINT,
  "CO_Company_Name" VARCHAR(100),
  "CRM_InsuredBy" TEXT,
  "CRM_CustomerName" TEXT,
  "LOG_DATE" DATE,
  "AAI_AI_NO" BIGINT,
  "AO_VEHICLE_ID" INTEGER,
  "AI_vehicle_make" VARCHAR(50),
  "AI_VEHICLE_MODEL" VARCHAR(50),
  "AI_VEHICLE_CHASISNO" VARCHAR(50),
  "AI_VEHICLE_ENGINENO" VARCHAR(50),
  "AI_VEHICLE_DOI" VARCHAR(50),
  "AI_VEHICLE_REGISTRATIONNO" VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS "CurrentMonthSummary" (
  "ATS_Date" DATE,
  "Bank Islami Pakistan Limited" DOUBLE PRECISION NOT NULL,
  "Dubai Islamic Bank Limited" DOUBLE PRECISION NOT NULL,
  "Meezan Bank Limited" DOUBLE PRECISION NOT NULL,
  "Total" DOUBLE PRECISION NOT NULL
);

CREATE TABLE IF NOT EXISTS "CancelInvoice" (
  "Date1" TIMESTAMP,
  "JE_VOUCHER_NO" DOUBLE PRECISION,
  "Narration" VARCHAR(255),
  "Particular" VARCHAR(255),
  "AI_NO" DOUBLE PRECISION,
  "Debit" DOUBLE PRECISION,
  credit DOUBLE PRECISION,
  "Balance" DOUBLE PRECISION,
  "Comment" VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS "CRM_VEHICLE_ID" (
  "CRM_VEHICLE_ID" BIGINT
);

CREATE TABLE IF NOT EXISTS "CRM_VEHICLESDETAILS" (
  "Vehicle_Id" BIGINT NOT NULL,
  "CustomerId" BIGINT,
  "PackageID" BIGINT,
  "Vehicle_Make" VARCHAR(50),
  "Vehicle_Model" VARCHAR(50),
  "Vehicle_Year" VARCHAR(50),
  "Vehicle_Color" VARCHAR(50),
  "Vehicle_CC" VARCHAR(50),
  "Vehicle_Transmission" VARCHAR(50),
  "Vehicle_EngineNo" VARCHAR(50),
  "Vehicle_ChasisNo" VARCHAR(50),
  "Vehicle_RegistrationNo" VARCHAR(50),
  "Vehicle_IsLeased" VARCHAR(3),
  "Vehicle_Leased_CompanyId" BIGINT,
  "Vehicle_Leased_ContactId" BIGINT,
  "Vehicle_Lessee" VARCHAR(100),
  "Vehicle_LeaseTeanure" VARCHAR(50),
  "Vehicle_IsInsured" VARCHAR(3),
  "Vehicle_Insurance_CompanyId" BIGINT,
  "Vehicle_Insurance_ContactId" BIGINT,
  "Vehicle_InsuranceValue" VARCHAR(50),
  "Vehicle_PaymentTerms" INTEGER,
  "Vehicle_TrackingPassword" VARCHAR(50),
  "Vehicle_TrackingAverageKmPerDay" INTEGER,
  "Vehicle_TrackingSpecialInstructions" TEXT,
  "Vehicle_DeviceSerial" TEXT,
  "Vehicle_SIM" TEXT,
  "Vehicle_SalesPersonName" VARCHAR(50),
  "Vehicle_SalesCode" INTEGER,
  "Vehicle_IMEINo" TEXT,
  "Vehicle_SalesOk" TEXT,
  "Vehicle_CICOk" TEXT,
  "Vehicle_DataCenterOk" TEXT,
  "Vehicle_SecurityOk" TEXT,
  "Vehicle_CallCenterOk" TEXT,
  "Vehicle_FinanceOk" TEXT,
  "Vehicle_AgreementDate" TEXT,
  "Vehicle_AgreementFiePath" TEXT,
  "Vehicle_BonnetLock" TEXT,
  "Vehicle_MName" TEXT,
  "Vehicle_Installation_location" TEXT,
  "Vehicle_PONo" VARCHAR(100),
  "Vehicle_Technician" VARCHAR(100),
  "FirstInstallment" INTEGER,
  "SecInstallment" INTEGER,
  "ThirdInstallment" INTEGER,
  "ForthInstallment" INTEGER,
  "FifthInstallment" INTEGER,
  "SixthInstallment" INTEGER,
  "LNL" VARCHAR(2),
  "Vehicle_Policy" INTEGER,
  "First_DueDate" INTEGER,
  "Second_DueDate" INTEGER,
  "Third_DueDate" INTEGER,
  "Forth_DueDate" INTEGER,
  "Fifth_DueDate" INTEGER,
  "Sixth_DueDate" INTEGER,
  "First_Closing" INTEGER,
  "Sec_Closing" INTEGER,
  "Third_Closing" INTEGER,
  "Forth_Closing" INTEGER,
  "Fifth_Closing" INTEGER,
  "Sixth_Closing" INTEGER,
  "Vehicle_Device" VARCHAR(50),
  "CustomerName" TEXT,
  "Address1" TEXT,
  "Address2" TEXT,
  "TelephoneNo" VARCHAR(50),
  "CellNo" TEXT,
  vehid BIGINT,
  "NIC" VARCHAR(100),
  "InsuredBy" TEXT,
  "Vehicle_DateOfInstallation" TIMESTAMP,
  "PRODUCT" VARCHAR(50),
  "CORPORATE_ID" BIGINT,
  "B_ID" BIGINT,
  "PACKAGE_TYPE" VARCHAR(50),
  "FLEET_TYPE" VARCHAR(30),
  "BRANCH_NAME" VARCHAR(100),
  "PO_SPECIAL_INSTRUCTIONS" TEXT,
  "OBJECTID" BIGINT,
  "Amount" DOUBLE PRECISION,
  "CommissionValue" DOUBLE PRECISION
);

CREATE TABLE IF NOT EXISTS "CRM_PaymentReceiptPosted" (
  "VehicleId" BIGINT NOT NULL,
  "Engine" VARCHAR(50),
  "Chassis" VARCHAR(50),
  "Amount" DOUBLE PRECISION,
  "Mode" VARCHAR(50),
  "PaymentFor" VARCHAR(50),
  "BankID" INTEGER,
  "AI_NO" BIGINT,
  "TaxDetails" TEXT,
  "NoOfTaxes" INTEGER,
  "RefNo" VARCHAR(100),
  "LogTime" TIMESTAMP,
  "PostingTime" TIMESTAMP,
  "PostedBy" VARCHAR(50),
  "DepositDate" TIMESTAMP,
  "ATS_Post_Date" TIMESTAMP,
  "ATS_Post" BOOLEAN,
  "TransID" BIGINT,
  "CustomerId" BIGINT,
  "AI_CO_ID" BIGINT,
  "AI_Amount" BIGINT,
  "AI_Date" TIMESTAMP,
  "APR_NO" BIGINT
);

CREATE TABLE IF NOT EXISTS "CRM_KJN001" (
  "Vehicle_Id" BIGINT NOT NULL,
  "CustomerId" BIGINT NOT NULL,
  "PackageID" BIGINT,
  "Vehicle_Make" VARCHAR(50),
  "Vehicle_Model" VARCHAR(50),
  "Vehicle_Year" VARCHAR(50),
  "Vehicle_Color" VARCHAR(50),
  "Vehicle_CC" VARCHAR(50),
  "Vehicle_Transmission" VARCHAR(9) NOT NULL,
  "Vehicle_EngineNo" VARCHAR(50),
  "Vehicle_ChasisNo" VARCHAR(50),
  "Vehicle_RegistrationNo" VARCHAR(50) NOT NULL,
  "Vehicle_IsLeased" VARCHAR(3) NOT NULL,
  "Vehicle_Leased_CompanyId" INTEGER,
  "Vehicle_Leased_ContactId" INTEGER,
  "Vehicle_Lessee" VARCHAR(50),
  "Vehicle_LeaseTeanure" INTEGER,
  "Vehicle_IsInsured" VARCHAR(3) NOT NULL,
  "Vehicle_Insurance_CompanyId" INTEGER,
  "Vehicle_Insurance_ContactId" INTEGER,
  "Vehicle_InsuranceValue" TEXT,
  "Vehicle_PaymentTerms" INTEGER,
  "Vehicle_TrackingPassword" VARCHAR(1) NOT NULL,
  "Vehicle_TrackingAverageKmPerDay" INTEGER,
  "Vehicle_TrackingSpecialInstructions" TEXT,
  "Vehicle_DeviceSerial" TEXT,
  "Vehicle_SIM" TEXT,
  "Vehicle_SalesPersonName" VARCHAR(50),
  "Vehicle_SalesCode" INTEGER,
  "Vehicle_IMEINo" TEXT,
  "Vehicle_SalesOk" INTEGER,
  "Vehicle_CICOk" INTEGER,
  "Vehicle_DataCenterOk" INTEGER,
  "Vehicle_SecurityOk" INTEGER,
  "Vehicle_CallCenterOk" INTEGER,
  "Vehicle_FinanceOk" INTEGER,
  "Vehicle_AgreementDate" INTEGER,
  "Vehicle_AgreementFiePath" INTEGER,
  "Vehicle_BonnetLock" INTEGER,
  "Vehicle_MName" INTEGER,
  "Vehicle_Installation_location" VARCHAR(100),
  "Vehicle_PONo" TEXT,
  "Vehicle_Technician" VARCHAR(50),
  "FirstInstallment" INTEGER,
  "SecInstallment" INTEGER,
  "ThirdInstallment" INTEGER,
  "ForthInstallment" INTEGER,
  "FifthInstallment" INTEGER,
  "SixthInstallment" INTEGER,
  "LNL" VARCHAR(2) NOT NULL,
  "Vehicle_Policy" INTEGER,
  "First_DueDate" INTEGER,
  "Second_DueDate" INTEGER,
  "Third_DueDate" INTEGER,
  "Forth_DueDate" INTEGER,
  "Fifth_DueDate" INTEGER,
  "Sixth_DueDate" INTEGER,
  "First_Closing" INTEGER,
  "Sec_Closing" INTEGER,
  "Third_Closing" INTEGER,
  "Forth_Closing" INTEGER,
  "Fifth_Closing" INTEGER,
  "Sixth_Closing" INTEGER,
  "Vehicle_Device" VARCHAR(50),
  "CustomerName" TEXT,
  "Address1" TEXT,
  "Address2" TEXT,
  "TelephoneNo" VARCHAR(1) NOT NULL,
  "CellNo" TEXT,
  vehid BIGINT NOT NULL,
  "NIC" TEXT,
  "InsuredBy" TEXT,
  "Vehicle_DateOfInstallation" TIMESTAMP,
  "PRODUCT" VARCHAR(50),
  "CORPORATE_ID" INTEGER,
  "B_ID" BIGINT,
  "PACKAGE_TYPE" VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS "CRM_ATS_PAYMENT_RECEIPT_V_TBL" (
  "APR_NO" BIGINT NOT NULL,
  "APR_DATE" TIMESTAMP,
  "APR_DESCRIPTION" VARCHAR(255),
  "APR_CO_ID" BIGINT,
  "APR_BANK_ID" INTEGER,
  "APR_POST" BOOLEAN,
  "APR_GL" BOOLEAN,
  "APR_Cancel" BOOLEAN,
  "AAI_AI_NO" BIGINT,
  "AAI_AI_DATE" TIMESTAMP,
  "AAI_AI_AMOUNT" DOUBLE PRECISION,
  "AAI_PEN_AMOUNT" DOUBLE PRECISION,
  "AAI_ADJUST" DOUBLE PRECISION,
  "AO_VEHICLE_ID" INTEGER,
  "AI_vehicle_make" VARCHAR(50),
  "AI_VEHICLE_MODEL" VARCHAR(50),
  "AI_VEHICLE_CHASISNO" VARCHAR(50),
  "AI_VEHICLE_ENGINENO" VARCHAR(50),
  "AI_VEHICLE_DOI" VARCHAR(50),
  "AI_VEHICLE_REGISTRATIONNO" VARCHAR(50),
  "CRM_TRANS_ID" BIGINT,
  "BANK_NAME" VARCHAR(100) NOT NULL,
  "CO_Company_Name" VARCHAR(100),
  "CRM_InsuredBy" TEXT,
  "CRM_CustomerName" TEXT,
  "LOG_DATETIME_INSERT" TIMESTAMP,
  "CO_Corporate" BOOLEAN
);

CREATE TABLE IF NOT EXISTS "CRM_AR_TAX_TEMP_TEST" (
  "RefNo" VARCHAR(100) NOT NULL,
  "TAXDETAILS" VARCHAR(200),
  "AI_NO" BIGINT,
  "APT_TD_ID" INTEGER,
  "APT_TAX_AMOUNT" DOUBLE PRECISION,
  "SEQNO" INTEGER
);

CREATE TABLE IF NOT EXISTS "CRM_AR_TAX_TEMP" (
  "RefNo" VARCHAR(100) NOT NULL,
  "TAXDETAILS" VARCHAR(200),
  "AI_NO" BIGINT,
  "APT_TD_ID" INTEGER,
  "APT_TAX_AMOUNT" DOUBLE PRECISION,
  "SEQNO" INTEGER
);

CREATE TABLE IF NOT EXISTS "CRM_250621" (
  "Vehicle_Id" BIGINT NOT NULL,
  "CustomerId" BIGINT NOT NULL,
  "PackageID" BIGINT,
  "Vehicle_Make" VARCHAR(50),
  "Vehicle_Model" VARCHAR(50),
  "Vehicle_Year" VARCHAR(50),
  "Vehicle_Color" VARCHAR(50),
  "Vehicle_CC" VARCHAR(50),
  "Vehicle_Transmission" VARCHAR(9) NOT NULL,
  "Vehicle_EngineNo" VARCHAR(50),
  "Vehicle_ChasisNo" VARCHAR(50),
  "Vehicle_RegistrationNo" VARCHAR(50) NOT NULL,
  "Vehicle_IsLeased" VARCHAR(3) NOT NULL,
  "Vehicle_Leased_CompanyId" INTEGER,
  "Vehicle_Leased_ContactId" INTEGER,
  "Vehicle_Lessee" VARCHAR(50),
  "Vehicle_LeaseTeanure" INTEGER,
  "Vehicle_IsInsured" VARCHAR(3) NOT NULL,
  "Vehicle_Insurance_CompanyId" INTEGER,
  "Vehicle_Insurance_ContactId" INTEGER,
  "Vehicle_InsuranceValue" TEXT,
  "Vehicle_PaymentTerms" INTEGER,
  "Vehicle_TrackingPassword" VARCHAR(1) NOT NULL,
  "Vehicle_TrackingAverageKmPerDay" INTEGER,
  "Vehicle_TrackingSpecialInstructions" TEXT,
  "Vehicle_DeviceSerial" TEXT,
  "Vehicle_SIM" TEXT,
  "Vehicle_SalesPersonName" VARCHAR(50),
  "Vehicle_SalesCode" INTEGER,
  "Vehicle_IMEINo" TEXT,
  "Vehicle_SalesOk" INTEGER,
  "Vehicle_CICOk" INTEGER,
  "Vehicle_DataCenterOk" INTEGER,
  "Vehicle_SecurityOk" INTEGER,
  "Vehicle_CallCenterOk" INTEGER,
  "Vehicle_FinanceOk" INTEGER,
  "Vehicle_AgreementDate" INTEGER,
  "Vehicle_AgreementFiePath" INTEGER,
  "Vehicle_DateOfInstallation" TIMESTAMP,
  "Vehicle_BonnetLock" INTEGER,
  "Vehicle_MName" INTEGER,
  "Vehicle_Installation_location" VARCHAR(100),
  "Vehicle_PONo" TEXT,
  "Vehicle_Technician" VARCHAR(50),
  "FirstInstallment" INTEGER,
  "SecInstallment" INTEGER,
  "ThirdInstallment" INTEGER,
  "ForthInstallment" INTEGER,
  "FifthInstallment" INTEGER,
  "SixthInstallment" INTEGER,
  "LNL" VARCHAR(2) NOT NULL,
  "Vehicle_Policy" INTEGER,
  "First_DueDate" INTEGER,
  "Second_DueDate" INTEGER,
  "Third_DueDate" INTEGER,
  "Forth_DueDate" INTEGER,
  "Fifth_DueDate" INTEGER,
  "Sixth_DueDate" INTEGER,
  "First_Closing" INTEGER,
  "Sec_Closing" INTEGER,
  "Third_Closing" INTEGER,
  "Forth_Closing" INTEGER,
  "Fifth_Closing" INTEGER,
  "Sixth_Closing" INTEGER,
  "Vehicle_Device" VARCHAR(50),
  "CustomerName" TEXT,
  "Address1" TEXT,
  "Address2" TEXT,
  "TelephoneNo" VARCHAR(1) NOT NULL,
  "CellNo" TEXT,
  vehid BIGINT NOT NULL,
  "NIC" TEXT,
  "InsuredBy" TEXT,
  "PRODUCT" VARCHAR(50),
  "CORPORATE_ID" INTEGER,
  "B_ID" BIGINT,
  "PACKAGE_TYPE" VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS "CRM_14062022" (
  "Vehicle_Id" BIGINT NOT NULL,
  "CustomerId" BIGINT,
  "PackageID" BIGINT,
  "Vehicle_Make" VARCHAR(50),
  "Vehicle_Model" VARCHAR(50),
  "Vehicle_Year" VARCHAR(50),
  "Vehicle_Color" VARCHAR(50),
  "Vehicle_CC" VARCHAR(50),
  "Vehicle_Transmission" VARCHAR(50),
  "Vehicle_EngineNo" VARCHAR(50),
  "Vehicle_ChasisNo" VARCHAR(50),
  "Vehicle_RegistrationNo" VARCHAR(50),
  "Vehicle_IsLeased" VARCHAR(3),
  "Vehicle_Leased_CompanyId" BIGINT,
  "Vehicle_Leased_ContactId" BIGINT,
  "Vehicle_Lessee" VARCHAR(100),
  "Vehicle_LeaseTeanure" VARCHAR(50),
  "Vehicle_IsInsured" VARCHAR(3),
  "Vehicle_Insurance_CompanyId" BIGINT,
  "Vehicle_Insurance_ContactId" BIGINT,
  "Vehicle_InsuranceValue" BIGINT,
  "Vehicle_PaymentTerms" INTEGER,
  "Vehicle_TrackingPassword" VARCHAR(50),
  "Vehicle_TrackingAverageKmPerDay" INTEGER,
  "Vehicle_TrackingSpecialInstructions" TEXT,
  "Vehicle_DeviceSerial" TEXT,
  "Vehicle_SIM" TEXT,
  "Vehicle_SalesPersonName" VARCHAR(50),
  "Vehicle_SalesCode" INTEGER,
  "Vehicle_IMEINo" TEXT,
  "Vehicle_SalesOk" TEXT,
  "Vehicle_CICOk" TEXT,
  "Vehicle_DataCenterOk" TEXT,
  "Vehicle_SecurityOk" TEXT,
  "Vehicle_CallCenterOk" TEXT,
  "Vehicle_FinanceOk" TEXT,
  "Vehicle_AgreementDate" TEXT,
  "Vehicle_AgreementFiePath" TEXT,
  "Vehicle_BonnetLock" TEXT,
  "Vehicle_MName" TEXT,
  "Vehicle_Installation_location" TEXT,
  "Vehicle_PONo" VARCHAR(100),
  "Vehicle_Technician" VARCHAR(100),
  "FirstInstallment" INTEGER,
  "SecInstallment" INTEGER,
  "ThirdInstallment" INTEGER,
  "ForthInstallment" INTEGER,
  "FifthInstallment" INTEGER,
  "SixthInstallment" INTEGER,
  "LNL" VARCHAR(2),
  "Vehicle_Policy" INTEGER,
  "First_DueDate" INTEGER,
  "Second_DueDate" INTEGER,
  "Third_DueDate" INTEGER,
  "Forth_DueDate" INTEGER,
  "Fifth_DueDate" INTEGER,
  "Sixth_DueDate" INTEGER,
  "First_Closing" INTEGER,
  "Sec_Closing" INTEGER,
  "Third_Closing" INTEGER,
  "Forth_Closing" INTEGER,
  "Fifth_Closing" INTEGER,
  "Sixth_Closing" INTEGER,
  "Vehicle_Device" VARCHAR(50),
  "CustomerName" TEXT,
  "Address1" TEXT,
  "Address2" TEXT,
  "TelephoneNo" VARCHAR(50),
  "CellNo" TEXT,
  vehid BIGINT,
  "NIC" VARCHAR(100),
  "InsuredBy" TEXT,
  "Vehicle_DateOfInstallation" TIMESTAMP,
  "PRODUCT" VARCHAR(50),
  "CORPORATE_ID" BIGINT,
  "B_ID" BIGINT,
  "PACKAGE_TYPE" VARCHAR(50),
  "FLEET_TYPE" VARCHAR(30),
  "BRANCH_NAME" VARCHAR(100),
  "PO_SPECIAL_INSTRUCTIONS" TEXT,
  "OBJECTID" BIGINT,
  "Amount" DOUBLE PRECISION,
  "CommissionValue" DOUBLE PRECISION
);

CREATE TABLE IF NOT EXISTS "COST_CENTER" (
  "CC_ID" CHAR(3) NOT NULL,
  "CC_NAME" VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS "Bank_Master" (
  "BANK_ID" INTEGER NOT NULL,
  "BANK_NAME" VARCHAR(100) NOT NULL,
  "BANK_AC_ID" BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS "AR_VEHICLE" (
  "AV_ID" INTEGER NOT NULL,
  "AV_Vehicle_Id" INTEGER NOT NULL,
  "AV_CO_ID" INTEGER NOT NULL,
  "AV_Vehicle_Make" VARCHAR(50),
  "AV_Vehicle_Model" VARCHAR(50),
  "AV_Vehicle_CC" VARCHAR(50),
  "AV_Vehicle_InsuranceValue" DOUBLE PRECISION,
  "AV_DD_ID" INTEGER,
  "AV_PD_ID" INTEGER
);

CREATE TABLE IF NOT EXISTS "AR_UE_MSTR" (
  "ENTRYTYPEID" INTEGER NOT NULL,
  "ENTRYNO" INTEGER NOT NULL,
  "JE_HEADER_ID" BIGINT NOT NULL,
  "AI_NO" BIGINT NOT NULL,
  "AI_DATE" TIMESTAMP NOT NULL,
  "VCHSTATUS" VARCHAR(50) NOT NULL,
  "AI_IM_ID" INTEGER NOT NULL,
  "JE_AC_ID" BIGINT NOT NULL,
  "JE_ENTERED_DR" DOUBLE PRECISION NOT NULL,
  "JE_ENTERED_CR" DOUBLE PRECISION NOT NULL,
  "CLOSE_FLAG" BOOLEAN
);

CREATE TABLE IF NOT EXISTS "AR_UE_ELEMENTS" (
  "EntryID" INTEGER NOT NULL,
  "IM_ID_UE" INTEGER,
  "IM_DESCRIPTION_UE" VARCHAR(100),
  "IM_AC_ID_UE" BIGINT,
  "IM_ID_E" INTEGER,
  "IM_DESCRIPTION_E" VARCHAR(100),
  "IM_AC_ID_E" BIGINT,
  "SEQNO" INTEGER
);

CREATE TABLE IF NOT EXISTS "AR_Prepared_Invoice_Table" (
  "AO_NO" BIGINT NOT NULL,
  "PRICE1" BIGINT,
  "PRICE2" BIGINT,
  "PRICE3" BIGINT,
  "PRICE4" BIGINT,
  "PRICE5" BIGINT,
  "PRICE6" BIGINT,
  "PRICE7" BIGINT,
  "PRICE8" BIGINT,
  "PRICE9" BIGINT,
  "PRICE10" BIGINT,
  "PRICE11" BIGINT,
  "PRICE12" BIGINT,
  "INV1" BIGINT,
  "INV2" BIGINT,
  "INV3" BIGINT,
  "INV4" BIGINT,
  "INV5" BIGINT,
  "INV6" BIGINT,
  "INV7" BIGINT,
  "INV8" BIGINT,
  "INV9" BIGINT,
  "INV10" BIGINT,
  "INV11" BIGINT,
  "INV12" BIGINT,
  "AO_DATE1" TIMESTAMP,
  "AO_DATE2" TIMESTAMP,
  "AO_DATE3" TIMESTAMP,
  "AO_DATE4" TIMESTAMP,
  "AO_DATE5" TIMESTAMP,
  "AO_DATE6" TIMESTAMP,
  "AO_DATE7" TIMESTAMP,
  "AO_DATE8" TIMESTAMP,
  "AO_DATE9" TIMESTAMP,
  "AO_DATE10" TIMESTAMP,
  "AO_DATE11" TIMESTAMP,
  "AO_DATE12" TIMESTAMP,
  "AO_MAFD" BOOLEAN,
  "Vehicle_DateOfInstallation" TIMESTAMP,
  "AO_MAFD_DATE" TIMESTAMP,
  "AO_CO_ID" BIGINT
);

CREATE TABLE IF NOT EXISTS "AR_Pending_Payment" (
  id INTEGER NOT NULL,
  "AI_NO" BIGINT,
  "First_SMSDate" TIMESTAMP,
  "First_SMS" BOOLEAN,
  "Second_SMSDate" TIMESTAMP,
  "Second_SMS" BOOLEAN,
  "Third_SMSDate" TIMESTAMP,
  "Third_SMS" BOOLEAN,
  "CLOSED" BOOLEAN,
  "cellNo" VARCHAR(50),
  closed_date TIMESTAMP,
  "engNo" VARCHAR(100),
  "MakeModel" VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS "AR_PAYMENT_TAX" (
  "APT_ID" BIGINT NOT NULL,
  "APT_APR_NO" BIGINT,
  "APT_TD_ID" BIGINT,
  "APT_TAX_AMOUNT" DOUBLE PRECISION
);

CREATE TABLE IF NOT EXISTS "AR_PAYMENT_RECEIPT_LOG" (
  "APR_NO" BIGINT,
  "PC_INSERT" VARCHAR(50),
  "LOG_DATETIME_INSERT" TIMESTAMP,
  "PC_UPDATE" VARCHAR(50),
  "LOG_DATETIME_UPDATE" TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "AR_PAYMENT_RECEIPT" (
  "APR_NO" BIGINT NOT NULL,
  "APR_DATE" TIMESTAMP,
  "APR_DESCRIPTION" VARCHAR(255),
  "APR_CO_ID" BIGINT,
  "APR_BANK_ID" INTEGER,
  "APR_RECEIPT_AMOUNT" DOUBLE PRECISION,
  "APR_POST" BOOLEAN,
  "APR_GL" BOOLEAN,
  "APR_Cancel" BOOLEAN,
  "apr_Can_date" TIMESTAMP,
  "apr_can_GL" BOOLEAN,
  "APR_CHQ_NO" VARCHAR(50),
  "PostedBy" VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS "AR_PACKAGE_DETAIL" (
  "PD_ID" INTEGER NOT NULL,
  "PD_DESCRIPTION" VARCHAR(50) NOT NULL,
  "PD_DETAIL_ID" INTEGER NOT NULL,
  "PD_PRICE" DOUBLE PRECISION NOT NULL,
  "PD_TM_ID" INTEGER,
  "PD_AC_ID" INTEGER
);

CREATE TABLE IF NOT EXISTS "AR_ORDER_V_TEMP" (
  "AO_ID" BIGINT,
  "AO_NO" BIGINT,
  "AO_DATE" TIMESTAMP,
  "AO_DESCRIPTION" VARCHAR(200),
  "AO_CO_ID" BIGINT,
  "AO_VEHICLE_ID" BIGINT,
  "AO_PACKAGE_NAME" VARCHAR(200),
  "AO_MAFD" BOOLEAN,
  "AO_DEACTIVE_DATE" TIMESTAMP,
  "AO_IM_ID" BIGINT,
  "AO_PRICE1" BIGINT,
  "AO_PRICE2" BIGINT,
  "AO_PRICE3" BIGINT,
  "AO_PRICE4" BIGINT,
  "AO_PRICE5" BIGINT,
  "AO_PRICE6" BIGINT,
  "AO_PRICE7" BIGINT,
  "AO_PRICE8" BIGINT,
  "AO_PRICE9" BIGINT,
  "AO_PRICE10" BIGINT,
  "AO_PRICE11" BIGINT,
  "AO_PRICE12" BIGINT,
  "AO_INV1_ID" BIGINT,
  "AO_INV2_ID" BIGINT,
  "AO_INV3_ID" BIGINT,
  "AO_INV4_ID" BIGINT,
  "AO_INV5_ID" BIGINT,
  "AO_INV6_ID" BIGINT,
  "AO_INV7_ID" BIGINT,
  "AO_INV8_ID" BIGINT,
  "AO_INV9_ID" BIGINT,
  "AO_INV10_ID" BIGINT,
  "AO_INV11_ID" BIGINT,
  "AO_INV12_ID" BIGINT,
  "IM_DESCRIPTION" VARCHAR(200),
  "CO_Company_Name" VARCHAR(200),
  "Vehicle_Make" VARCHAR(200),
  "Vehicle_Model" VARCHAR(200),
  "Vehicle_EngineNo" VARCHAR(200),
  "Vehicle_ChasisNo" VARCHAR(200),
  "Vehicle_RegistrationNo" VARCHAR(200),
  "Vehicle_PONo" VARCHAR(200),
  "CustomerName" VARCHAR(200),
  "Address1" VARCHAR(200),
  "Address2" VARCHAR(200),
  "TelephoneNo" VARCHAR(200),
  "Vehicle_DateOfInstallation" TIMESTAMP,
  "AO_MAFD_DATE" TIMESTAMP,
  "NIC" VARCHAR(200),
  "AO_BookingCat" VARCHAR(200),
  "InsuredBy" VARCHAR(200),
  "PRODUCT" VARCHAR(200),
  "CORPORATE_ID" BIGINT,
  "PACKAGE_TYPE" VARCHAR(200),
  "CustomerId" BIGINT,
  vehid BIGINT,
  "Vehicle_Id" BIGINT,
  "ObjectID" BIGINT,
  "Price" BIGINT
);

CREATE TABLE IF NOT EXISTS "AR_ORDER" (
  "AO_ID" BIGINT NOT NULL,
  "AO_NO" INTEGER NOT NULL,
  "AO_DATE" TIMESTAMP NOT NULL,
  "AO_DESCRIPTION" VARCHAR(200),
  "AO_CO_ID" INTEGER,
  "AO_VEHICLE_ID" VARCHAR(50),
  "AO_PACKAGE_NAME" VARCHAR(50),
  "AO_MAFD" BOOLEAN,
  "AO_DEACTIVE_DATE" TIMESTAMP,
  "AO_IM_ID" INTEGER,
  "AO_PRICE1" DOUBLE PRECISION,
  "AO_PRICE2" DOUBLE PRECISION,
  "AO_PRICE3" DOUBLE PRECISION,
  "AO_PRICE4" DOUBLE PRECISION,
  "AO_PRICE5" DOUBLE PRECISION,
  "AO_PRICE6" DOUBLE PRECISION,
  "AO_PRICE7" DOUBLE PRECISION,
  "AO_PRICE8" DOUBLE PRECISION,
  "AO_PRICE9" DOUBLE PRECISION,
  "AO_PRICE10" DOUBLE PRECISION,
  "AO_PRICE11" DOUBLE PRECISION,
  "AO_PRICE12" DOUBLE PRECISION,
  "AO_INV1_ID" INTEGER,
  "AO_INV2_ID" INTEGER,
  "AO_INV3_ID" INTEGER,
  "AO_INV4_ID" INTEGER,
  "AO_INV5_ID" INTEGER,
  "AO_INV6_ID" INTEGER,
  "AO_INV7_ID" INTEGER,
  "AO_INV8_ID" INTEGER,
  "AO_INV9_ID" INTEGER,
  "AO_INV10_ID" INTEGER,
  "AO_INV11_ID" DOUBLE PRECISION,
  "AO_INV12_ID" DOUBLE PRECISION,
  "AO_MAFD_DATE" TIMESTAMP,
  "AO_BookingCat" VARCHAR(50),
  "SeqNo" INTEGER
);

CREATE TABLE IF NOT EXISTS "AR_INVOICE_TEMP" (
  "AIT_NO" VARCHAR(50) NOT NULL,
  "AIT_DATE" TIMESTAMP,
  "AIT_AO_NO" INTEGER,
  "AIT_PACKAGE_NAME" VARCHAR(50),
  "AIT_IM_ID" INTEGER NOT NULL,
  "AIT_AMOUNT" DOUBLE PRECISION,
  "AIT_vehicle_make" VARCHAR(50),
  "AIT_VEHICLE_MODEL" VARCHAR(50),
  "AIT_VEHICLE_ENGINENO" VARCHAR(50),
  "AIT_VEHICLE_CHASISNO" VARCHAR(50),
  "AIT_VEHICLE_PONO" VARCHAR(50),
  "AIT_VEHICLE_REGISTRATIONNO" VARCHAR(50),
  "AIT_CUSTOMER_NIC" VARCHAR(50),
  "AIT_CUSTOMER_NAME" VARCHAR(50),
  "AIT_TYPE" VARCHAR(50),
  "AIT_COL" INTEGER,
  "AIT_VEHICLE_DOI" VARCHAR(50),
  "AITID" INTEGER,
  "AIT_ID" INTEGER,
  "AO_BookingCat" VARCHAR(50),
  "AI_TEMP_POST" BIGINT
);

CREATE TABLE IF NOT EXISTS "AR_INVOICE_ELEMENTS" (
  "IM_ID" INTEGER NOT NULL,
  "IM_DESCRIPTION" VARCHAR(100),
  "IM_AC_ID" BIGINT,
  "IM_TM_ID" INTEGER,
  "IM_EXP_DAYS" INTEGER,
  "IM_EXP_ON" VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS "AR_INVOICE_AGEING" (
  "AI_NO" BIGINT,
  "AI_DATE" TIMESTAMP,
  "AI_CO_ID" BIGINT,
  "ORG_AMT" DOUBLE PRECISION,
  "PEN_AMT" DOUBLE PRECISION,
  "VEHICLE_ENGINENO" VARCHAR(50),
  "VEHICLE_DOI" VARCHAR(50),
  "Inv_Type" VARCHAR(7) NOT NULL
);

CREATE TABLE IF NOT EXISTS "AR_INVOICE" (
  "AI_NO" BIGINT NOT NULL,
  "AI_DATE" TIMESTAMP,
  "AI_AO_NO" INTEGER,
  "AI_PACKAGE_NAME" VARCHAR(50),
  "AI_IM_ID" INTEGER,
  "AI_AMOUNT" DOUBLE PRECISION,
  "AI_vehicle_make" VARCHAR(50),
  "AI_VEHICLE_MODEL" VARCHAR(50),
  "AI_VEHICLE_ENGINENO" VARCHAR(50),
  "AI_VEHICLE_CHASISNO" VARCHAR(50),
  "AI_VEHICLE_PONO" VARCHAR(50),
  "AI_VEHICLE_REGISTRATIONNO" VARCHAR(50),
  "AI_CUSTOMER_NAME" VARCHAR(50),
  "AI_CUSTOMER_NIC" VARCHAR(50),
  "AI_TYPE" VARCHAR(50),
  "AI_BILL_POST" BOOLEAN,
  "AI_POST" BOOLEAN,
  "AI_CO_ID" INTEGER,
  "AI_VEHICLE_DOI" VARCHAR(50),
  "AI_INV_GL" BOOLEAN,
  "AI_CANCEL" BOOLEAN,
  "AI_CAN_GL" BOOLEAN,
  "AI_CANCEL_DATE" TIMESTAMP,
  "AO_BookingCat" VARCHAR(50),
  "AI_INV_DOI" TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "AR_DEAL_MASTER" (
  "ADM_ID" INTEGER NOT NULL,
  "ADM_AC_ID" INTEGER NOT NULL,
  "ADM_AV_Vehicle_Make" VARCHAR(50),
  "ADM_AV_Vehicle_Model" VARCHAR(50),
  "ADM_AV_Vehicle_CC" VARCHAR(50),
  "ADM_Vehicle_Value" DOUBLE PRECISION,
  "ADM_UNIT_VALUE" DOUBLE PRECISION,
  "ADM_UNIT_AGE" DOUBLE PRECISION,
  "ADM_RENTAL_VALUE" DOUBLE PRECISION,
  "ADM_RENTAL_AGE" DOUBLE PRECISION,
  "ADM_DEALER_COMMISSION" DOUBLE PRECISION,
  "ADM_DEALER_POINTS" DOUBLE PRECISION,
  "ADM_SALES_COMMISSION" DOUBLE PRECISION
);

CREATE TABLE IF NOT EXISTS "AR_DEAL_DETAIL" (
  "DD_ID" INTEGER NOT NULL,
  "DD_DESCRIPTION" VARCHAR(50) NOT NULL,
  "DD_CO_ID" INTEGER NOT NULL,
  "DD_VEHICLE_MAKE" VARCHAR(50),
  "DD_VEHICLE_MODEL" VARCHAR(50),
  "DD_VEHICLE_CC" BIGINT,
  "DD_VEHICLE_VALUE" BIGINT,
  "DD_RBFY" BOOLEAN,
  "DD_TTLINS" INTEGER,
  "DD_INST" INTEGER,
  "DD_MAFD" BOOLEAN,
  "DD_DETAIL_ID" INTEGER NOT NULL,
  "DD_PRICE1" DOUBLE PRECISION,
  "DD_AGE1" DOUBLE PRECISION,
  "DD_PRICE2" DOUBLE PRECISION,
  "DD_AGE2" DOUBLE PRECISION,
  "DD_PRICE3" DOUBLE PRECISION,
  "DD_AGE3" DOUBLE PRECISION,
  "DD_PRICE4" DOUBLE PRECISION,
  "DD_AGE4" DOUBLE PRECISION,
  "DD_TM_ID" INTEGER,
  "DD_AC_ID" INTEGER
);

CREATE TABLE IF NOT EXISTS "AR_Companies" (
  "CO_ID" INTEGER NOT NULL,
  "CRDays" INTEGER,
  "CO_Company_Id" INTEGER,
  "CO_Company_Name" VARCHAR(100),
  "CO_AC_ID" BIGINT,
  co_strno VARCHAR(50),
  co_ntnno VARCHAR(50),
  co_address VARCHAR(200),
  co_opbal_r DOUBLE PRECISION,
  "CO_Corporate" BOOLEAN
);

CREATE TABLE IF NOT EXISTS "AR_CREDIT_NOTE" (
  "ACN_NO" BIGINT NOT NULL,
  "ACN_DATE" TIMESTAMP,
  "ACN_AI_NO" INTEGER,
  "ACN_NAME" VARCHAR(50),
  "ACN_IM_ID" INTEGER NOT NULL,
  "ACN_AMOUNT" DOUBLE PRECISION,
  "ACN_TYPE" VARCHAR(50),
  "ACN_POST" BOOLEAN,
  "ACN_INV_GL" BOOLEAN,
  "ACN_CO_ID" BIGINT,
  "ACN_DESCR" VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS "AR_ADJUST_INVOICE" (
  "AAI_ID" BIGINT NOT NULL,
  "AAI_APR_NO" BIGINT,
  "AAI_AI_NO" BIGINT,
  "AAI_AI_DATE" TIMESTAMP,
  "AAI_AI_AMOUNT" DOUBLE PRECISION,
  "AAI_PEN_AMOUNT" DOUBLE PRECISION,
  "AAI_ADJUST" DOUBLE PRECISION,
  "AAI_CO_ID" INTEGER
);

CREATE TABLE IF NOT EXISTS "AP_SUPPLIER" (
  "AS_ID" INTEGER NOT NULL,
  "AS_Supplier_Name" VARCHAR(100),
  "AS_AC_ID" BIGINT,
  "AS_strno" VARCHAR(50),
  "AS_ntnno" VARCHAR(50),
  "AS_address" VARCHAR(200),
  "AS_opbal_r" DOUBLE PRECISION,
  "CRDays" INTEGER
);

CREATE TABLE IF NOT EXISTS "AP_PAYMENT_TAX" (
  "APT_ID" BIGINT NOT NULL,
  "APT_APR_NO" BIGINT,
  "APT_TD_ID" BIGINT,
  "APT_TAX_AMOUNT" DOUBLE PRECISION
);

CREATE TABLE IF NOT EXISTS "AP_PAYMENT_RECEIPT" (
  "APR_NO" BIGINT NOT NULL,
  "APR_DATE" TIMESTAMP,
  "APR_DESCRIPTION" VARCHAR(100),
  "APR_AS_ID" BIGINT,
  "APR_BANK_ID" INTEGER,
  "APR_PAYMENT_AMOUNT" DOUBLE PRECISION,
  "APR_POST" BOOLEAN,
  "APR_GL" BOOLEAN,
  "APR_Cancel" BOOLEAN,
  "apr_Can_date" TIMESTAMP,
  "apr_can_GL" BOOLEAN,
  "APR_CHQ_NO" VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS "AP_INV_DEL_DATA" (
  "AI_AO_AC_ID" VARCHAR(10),
  "AI_AMOUNT" BIGINT
);

CREATE TABLE IF NOT EXISTS "AP_INVOICE" (
  "AI_NO" BIGINT NOT NULL,
  "AI_DATE" TIMESTAMP,
  "AI_REMARKS" VARCHAR(255),
  "AI_SUPPLIER_REF" VARCHAR(50),
  "AI_AC_ID" INTEGER,
  "AI_RMKS" VARCHAR(255),
  "AI_AMOUNT" DOUBLE PRECISION,
  "AI_TYPE" VARCHAR(50),
  "AI_POST" BOOLEAN,
  "AI_AS_ID" INTEGER,
  "AI_CANCEL" BOOLEAN,
  "AI_CANCEL_DATE" TIMESTAMP,
  "AI_INV_GL" BOOLEAN,
  "AI_CAN_GL" BOOLEAN,
  "AI_PAY_TO" VARCHAR(50),
  "AI_TM_ID" INTEGER,
  "AP_APR_NO" BIGINT
);

CREATE TABLE IF NOT EXISTS "AP_DEBIT_NOTE" (
  "ACN_NO" BIGINT NOT NULL,
  "ACN_DATE" TIMESTAMP,
  "ACN_AI_NO" INTEGER,
  "ACN_NAME" VARCHAR(50),
  "ACN_CC_ID" INTEGER,
  "ACN_AMOUNT" DOUBLE PRECISION,
  "ACN_TYPE" VARCHAR(50),
  "ACN_POST" BOOLEAN,
  "ACN_INV_GL" BOOLEAN,
  "ACN_AS_ID" BIGINT,
  "ACN_TM_ID" INTEGER
);

CREATE TABLE IF NOT EXISTS "AP_ADJUST_INVOICE" (
  "AAI_ID" BIGINT NOT NULL,
  "AAI_APR_NO" BIGINT,
  "AAI_AI_NO" BIGINT,
  "AAI_AI_DATE" TIMESTAMP,
  "AAI_AI_AMOUNT" DOUBLE PRECISION,
  "AAI_PEN_AMOUNT" DOUBLE PRECISION,
  "AAI_ADJUST" DOUBLE PRECISION,
  "AAI_AS_ID" INTEGER
);

CREATE TABLE IF NOT EXISTS "ACCOUNT_COMBINATION" (
  "COMBINATION_ID" BIGINT NOT NULL,
  "SEGMENT1" CHAR(4) NOT NULL,
  "SEGMENT2" CHAR(3) NOT NULL,
  "SEGMENT3" CHAR(6) NOT NULL,
  "SEGMENT4" CHAR(4) NOT NULL,
  "ACTIVE" BOOLEAN NOT NULL,
  "NoteID" DOUBLE PRECISION
);
