-- Primary keys, unique constraints, and foreign keys
-- Run after 10-ats_gl-schema-tables.sql

ALTER TABLE "AP_DEBIT_NOTE" ADD CONSTRAINT "PK_AP_DEBIT_NOTE" PRIMARY KEY ("ACN_NO");
ALTER TABLE "AR_CREDIT_NOTE" ADD CONSTRAINT "PK_AR_CREDIT_NOTE" PRIMARY KEY ("ACN_NO", "ACN_IM_ID");
ALTER TABLE "AR_INVOICE_ELEMENTS" ADD CONSTRAINT "PK_AR_INVOICE_ELEMENTS" PRIMARY KEY ("IM_ID");
ALTER TABLE "AR_Pending_Payment" ADD CONSTRAINT pkey_id PRIMARY KEY (id);
ALTER TABLE "je_Data_LOG" ADD CONSTRAINT "PK_je_Data_LOG" PRIMARY KEY (logid);
ALTER TABLE sysdiagrams ADD CONSTRAINT "PK__sysdiagrams__4CA06362" PRIMARY KEY (diagram_id);
ALTER TABLE "Users" ADD CONSTRAINT "PK__Users__3213E83FDF8C0F83" PRIMARY KEY (id);

ALTER TABLE sysdiagrams ADD CONSTRAINT "UK_principal_name" UNIQUE (principal_id, name);
ALTER TABLE "Users" ADD CONSTRAINT "UQ__Users__F3DBC5724555D21D" UNIQUE (username);
